export const authTypes = {
    SIGN_IN_REQUEST:'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE:'SIGN_IN_FAILURE',
    LOGOUT_SUCESS: 'LOGOUT_SUCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userTypes = {
    GET_REALTIME_USERS_REQUEST: 'GET_REALTIME_USERS_REQUEST',
    GET_REALTIME_USERS_SUCCESS: 'GET_REALTIME_USERS_SUCCESS',
    GET_REALTIME_USERS_FAILURE: 'GET_REALTIME_USERS_FAILURE',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE'
}